"""army table update

Revision ID: 34e74e489705
Revises: 4a5d2635773e
Create Date: 2019-05-21 10:54:45.247641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e74e489705'
down_revision = '4a5d2635773e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('army', sa.Column('number_squads', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('army', 'number_squads')
    # ### end Alembic commands ###
