"""empty message

Revision ID: 54835f45b4cb
Revises: 
Create Date: 2019-05-24 10:41:26.546951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54835f45b4cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('army',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('number_squads', sa.Integer(), nullable=True),
    sa.Column('webhook_url', sa.String(length=120), nullable=True),
    sa.Column('access_token', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('join_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token')
    )
    op.create_table('battle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attack_army_id', sa.Integer(), nullable=True),
    sa.Column('attack_army_name', sa.String(length=64), nullable=True),
    sa.Column('defence_army_id', sa.Integer(), nullable=True),
    sa.Column('defence_army_name', sa.String(length=64), nullable=True),
    sa.Column('defence_army_number_squads', sa.Integer(), nullable=True),
    sa.Column('attack_army_number_squads', sa.Integer(), nullable=True),
    sa.Column('num_of_attacks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battle')
    op.drop_table('army')
    # ### end Alembic commands ###
