"""empty message

Revision ID: 80aac2babac7
Revises: a62a8f18ba8f
Create Date: 2019-05-22 10:26:07.208842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80aac2babac7'
down_revision = 'a62a8f18ba8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('army', sa.Column('access_token', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('army', 'access_token')
    # ### end Alembic commands ###
