"""empty message

Revision ID: e91819f10f03
Revises: 34e74e489705
Create Date: 2019-05-22 09:43:52.665426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91819f10f03'
down_revision = '34e74e489705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('army', sa.Column('status', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('army', 'status')
    # ### end Alembic commands ###
